### ISSUE TITLE
it is showing errror i should say the following message is displayed

### ISSUE THREAD

**Issue by BrandedAlok** [StevePaget/Pygame_Functions#1]
it is showing errror i should say the following message is displayed

python pygame_functions.py
pygame_functions is not designed to be run directly.

now please tell how to run it dear sir

**Comment by StevePaget** [comment]
Hi Alok,

You don't run the Pygame functions file. You import it into your own
program and use the commands.

Look at the files in the demo folder to see how it's used, or read the wiki
page here:
https://github.com/StevePaget/Pygame_Functions/wiki/Getting-Started

**Comment by BrandedAlok** [comment]
C:\>python -m pip install pygame-1.9.3-cp36-cp36m-win_amd64.whl
Requirement already satisfied: pygame==1.9.3 from file:///C:/pygame-1.9.3-cp36-cp36m-win_amd64.whl in c:\users\user\anaconda3\lib\site-packages


>python RocketDemo3.py
Traceback (most recent call last):
  File "RocketDemo3.py", line 1, in <module>
    from pygame_functions import *
ModuleNotFoundError: No module named 'pygame_functions'

Dear sir it is still displaying the same error
one side it is saying requirement already satisfied and other side it is saying no module named 'pygame_functions'

**Comment by StevePaget** [comment]
Depending on your setup, it might not be finding the copy of pygame_functions that's in the folder above /demos

Try copying the pygame_functions.py file into the /demos folder before running, or move the demo file you want to try.

**Comment by BrandedAlok** [comment]
![problem](https://user-images.githubusercontent.com/21073030/28724584-2fb7feda-73d8-11e7-9244-97be0a35b948.jpg)

Dear sir as you told i did the same exactly its still displaying the same error.

from pygame_functions import *
ModuleNotFoundError: No module named 'pygame_functions'

**Comment by StevePaget** [comment]
It look like you have copied the Pygame installer file into that folder. You need the file called pygame_functions.py

**Comment by StevePaget** [comment]
I have updated the repository so that a copy of this file is in the demos folder.

**Comment by StevePaget** [comment]
Closing this as I think I've solved it. If not, please open another issue.
