### ISSUE TITLE
Introduction Screen Video Initialization Error

### ISSUE THREAD

**Issue by JABeal** [StevePaget/Pygame_Functions#17]
Hi Steve,

I have been using your pygame_functions file to create my first game.

It is a simple space game exactly like your rocket.demo video.

I am working on inputting an introduction screen that utilizes spacebar to start the game and the letter q to exit.

Here is my code so far:

`#Set up introduction screen

def game_intro():

    intro = True

    while intro:

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                end()

            if event.type == pygame.KEYDOWN:
                if keyPressed == "space":
                    intro = False
                if keyPressed == "q":
                    end()
                
        
        screenSize(450,300)
        setBackgroundImage("intro_background.png")

        titleLabel = makeLabel("SPACE RACER!", 45, 70, 0, "green", "Comic Sans MS")
        showLabel(titleLabel)

        directionLabel = makeLabel("Use the directional keys to guide your spaceship!", 15, 60, 180, "green", "Comic Sans MS")
        showLabel(directionLabel)

        entryLabel = makeLabel("Press the SPACEBAR to begin or Q to quit.", 15, 80, 200, "green", "Comic Sans MS")
        showLabel(entryLabel)

game_intro()`

So far the commands do not work and the screen blips rapidly. I think I am bypassing a predefined function that you may have made in your file, but I am pretty new to all this and am not sure.

The error message reads...

Traceback (most recent call last):
  File "C:\Users\Justin Beal\Desktop\Python Files\Space_Racer.py", line 40, in <module>
    game_intro()
  File "C:\Users\Justin Beal\Desktop\Python Files\Space_Racer.py", line 27, in game_intro
    screenSize(450,300)
  File "C:\Users\Justin Beal\Desktop\Python Files\pygame_functions.py", line 294, in screenSize
    windowInfo = pygame.display.Info()
pygame.error: video system not initialized

Any idea what I am doing wrong?

**Comment by StevePaget** [comment]
You should only use ScreenSize once, near the start of your program. That makes the window that you use for the rest of the game.
At the moment you have that in a loop so it's trying to make loads of windows.
