### ISSUE TITLE
KillSprite

### ISSUE THREAD

**Issue by chubis26** [StevePaget/Pygame_Functions#2]
from pygame_functions import *
import time

screenSize(1280,900)
setBackgroundImage("stars.png")
hydro = makeSprite("elementletter/H1.png")
addSpriteImage(hydro,"elementletter/H2.png")
addSpriteImage(hydro,"elementletter/H3.png")
moveSprite(hydro, 50, 300)
showSprite(hydro)
changeSpriteImage(hydro,1)
time.sleep(0.5)
changeSpriteImage(hydro,0)
time.sleep(0.5)
changeSpriteImage(hydro,2)
time.sleep(0.5)
changeSpriteImage(hydro,0)
time.sleep(0.5)
    
killSprite(hydro)

--I need to kill the sprite after the changing it..

**Comment by chubis26** [comment]
![321](https://user-images.githubusercontent.com/30973634/29248318-f3b1ea7e-7fc9-11e7-933d-f5a10370e796.jpg)

**Comment by StevePaget** [comment]
This has been fixed. killSprite() didn't update the screen afterwards, but now it does.

Incidentally, I have also added hideAll() function, to fix your other request. This hides all currently displayed sprites.

**Comment by chubis26** [comment]
thank you will try it now..
paget can i ask again ?
how can i let the python
for wait the keypressed for 1secs
then if key is not pressed it will continue the program
or
how can i make python
run a loop and that has inputbox to it
and anytime i want to pushed to UP button(keypressed)
i can break out from the loop

**Comment by StevePaget** [comment]
Wait for a second unless key pressed:

`from pygame_functions import *

screenSize(300,200)
setBackgroundColour("blue")
infoLabel = makeLabel("Ready",44,100,100)
showLabel(infoLabel)

pause(1000)
changeLabel(infoLabel,"3")
pause(1000)
changeLabel(infoLabel,"2")
pause(1000)
changeLabel(infoLabel,"1")
pause(1000)
setBackgroundColour("red")
changeLabel(infoLabel,"Go")

# wait for 1 second unless a key is pressed
start = clock()
print(start)
pressed = False
while clock() < start+1000:
    if keyPressed():
        changeLabel(infoLabel,"key pressed")
        pressed = True
        break

if not pressed:
    changeLabel(infoLabel,"Time")

endWait()
`


Wait until Up pressed:

`from pygame_functions import *

screenSize(300,200)
setBackgroundColour("blue")
infoLabel = makeLabel("Ready",44,100,100)
showLabel(infoLabel)

pause(1000)
changeLabel(infoLabel,"3")
pause(1000)
changeLabel(infoLabel,"2")
pause(1000)
changeLabel(infoLabel,"1")
pause(1000)
setBackgroundColour("red")
changeLabel(infoLabel,"Go")

# wait until up key pressed
while True:
    if keyPressed("up"):
        break

changeLabel(infoLabel,"Up pressed")

endWait()`

**Comment by chubis26** [comment]
thank you paget.. we  will have your name in our paper for the help.. thanks a lot...

**Comment by StevePaget** [comment]
Cool. Make sure you grab the latest version, keyPressed wasn't quite working right if you didn't specify a key, but has been fixed now.

**Comment by chubis26** [comment]
#Wait for a second unless key pressed:

from pygame_functions import *

screenSize(300,200)
setBackgroundColour("blue")

# wait for 1 second unless a key is pressed
start = clock()
button5=Button(26)
print(start)
pressed = False
while True:
    infoLabel = makeLabel("Ready",44,100,100)
    showLabel(infoLabel)
   pause(1000)
    changeLabel(infoLabel,"3")
    pause(1000)
    changeLabel(infoLabel,"2")
    pause(1000)
    changeLabel(infoLabel,"1")
    pause(1000)
    setBackgroundColour("red")
    changeLabel(infoLabel,"Go")
    while clock() < start+1000:
        if keyPressed("up"):
            changeLabel(infoLabel,"key pressed")
            pressed = True
    if not pressed:
        changeLabel(infoLabel,"Time")

endWait()


i want to this in the loop... i want the background get blue again after the go signal....
but it turns out like this
![get](https://user-images.githubusercontent.com/30973634/29296104-0bbf8b0a-810d-11e7-96ed-53f233f3d2b5.png)

**Comment by StevePaget** [comment]
OK, I'm guessing you want it to repeat over and over, so you have wrapped the whole thing in a while loop, but you've introduced a few problems. I'll comment about them...

```
from pygame_functions import *

screenSize(300,200)
setBackgroundColour("blue") # if you want the screen to go blue when it starts each countdown, 
#this needs to be moved into the While loop

start = clock()  # This line records the current time, so you can compare the time later and see 
# if a  second has passed. However, if you put this outside the While loop, there's a big delay
# until the bit where you check to see if a second has passed, so it's already too late. In effect,
# this needs moving!

print(start)
pressed = False
while True:
    infoLabel = makeLabel("Ready",44,100,100)  # makeLabel creates a new label object. Because
# this is inside the while loop, it's creating multiple text labels which is why you can see more
# than one piece of text on top of one another. You should only make one label, outside the
# loop. So this also needs moving!

    showLabel(infoLabel)
   pause(1000)
    changeLabel(infoLabel,"3")
    pause(1000)
    changeLabel(infoLabel,"2")
    pause(1000)
    changeLabel(infoLabel,"1")
    pause(1000)
    setBackgroundColour("red")
    changeLabel(infoLabel,"Go")
    while clock() < start+1000:
        if keyPressed("up"):
            changeLabel(infoLabel,"key pressed")
            pressed = True
    if not pressed:
        changeLabel(infoLabel,"Time")

endWait()
```

I think you're after something like this:

```
from pygame_functions import *

screenSize(300,200)
infoLabel = makeLabel("Ready", 44, 100, 100)
showLabel(infoLabel)

while True:
    setBackgroundColour("blue")
    changeLabel(infoLabel,"3")
    pause(1000)
    changeLabel(infoLabel,"2")
    pause(1000)
    changeLabel(infoLabel,"1")
    pause(1000)
    setBackgroundColour("red")
    changeLabel(infoLabel,"Go")
    start = clock()
    pressed = False
    while clock() < start+1000:
        if keyPressed("up"):
            changeLabel(infoLabel,"key pressed")
            pressed = True
    if not pressed:
        changeLabel(infoLabel,"Time")
    pause(1000)

endWait()
```

**Comment by chubis26** [comment]
ok paget... will read this tonight... and will understand in as a whole.. sorry mate for asking a lot of question but i really struggle in programming..

**Comment by chubis26** [comment]
from threading import Thread
import time
def dd1():
    counter=0
    while True:
        while True:
            while True:
                while counter <10:
                    counter=counter+1
                    print(counter)
                    if counter == 9:
                        break
                print('no4')
                break
            print('no3')
            break
        print('no1')
        break
    print('no1')

def dd2():
    timer=30
    while timer>0:
        print(timer)
        time.sleep(0.25)
        timer=timer-1
    print('time finish')

def dd3():
    Thread(target=dd1).start()
    Thread(target=dd2).start()

def dd4():
    com=4
    while com>1:
        dd3()
        print(com)
        com=com-1
    print('finish')

dd4()

**Comment by chubis26** [comment]
can i run the dd3():  three or more time in a loop that i will set up?

**Comment by chubis26** [comment]
from threading import Thread
import time
def dd1():
    counter=0
    while True:
        while True:
            while True:
                while counter <10:
                    counter=counter+1
                    print(counter)
                    if counter == 9:
                        break
                print('no4')
                break
            print('no3')
            break
        print('no1')
        break
    print('no1')

def dd2():
    timer=30
    while timer>0:
        print(timer)
        time.sleep(0.25)
        timer=timer-1
    print('time finish')

def dd3():
    Thread(target=dd1).start()
    Thread(target=dd2).start()

def dd4():
    com=4
    while com>1:
        dd3()
        print(com)
        com=com-1
    print('finish')

dd4()

**Comment by StevePaget** [comment]
I'm not sure what this program is trying to do. Can you explain?
