### ISSUE TITLE
Rotate Background

### ISSUE THREAD

**Issue by AndreescuC** [StevePaget/Pygame_Functions#27]
Hi Steve,

Firstly, thank you for this helpful library!

I just started using it, and my aim is to create a game that has a central actor that moves around a dynamic map (the actor stays centered, no translation, no rotation, while the background transforms accordingly). 

I have been using the setBackgroundImage functionality and while the translation is simple to emulate using the scrollBackground function, I wonder if is there any "rotateBackground" functionality. If not, do you have any quick suggestions on how I should implement it in the already defined Background class?

I've tried using pygame_function.transformSprite and pygame.transform.rotate but I'm not quite sure on which of the Background's class internals I should apply it on.

Thanks!

**Comment by StevePaget** [comment]
Hi Andreescu,

I think you're going to have trouble rotating the background with the current class as it is. Especially if you try to scroll it too!
If it's a static image, you could try using pygame's rotate function on Background.tiles[0][0], which holds the image of a one-tile background. I think it will look messy though. There will be blank corners.

**Comment by AndreescuC** [comment]
Thank you for the reply,

Indeed, rotating the tiles looks messy and breaks continuity. After some more investigation, I chose to go with a more simple approach, using the pygame's rotate function on a Surface, which represents my background, without making use of Background objects anymore. And that seems to work fine. 

Thanks alot for your feedback, Steve!
