### ISSUE TITLE
No setWindowTitle or setIcon

### ISSUE THREAD

**Issue by SP4R0W** [StevePaget/Pygame_Functions#33]
Hi I wanted to change the title and icon of my game but I can't find the options for it in pygame_functions. Is there any way to change it now?

**Comment by zerokrezan** [comment]
Yeah, you can actually do it without the help of pygame_functions. So you can put a title above the pygame window and you can put a icon to your window on left above too.

**Comment by comport9** [comment]
```
pygame.display.set_caption("Your Game Title")
gameIcon =  pygame.image.load('Your_Icon.png')
pygame.display.set_icon(gameIcon)
```

**Comment by StevePaget** [comment]
These have been replaced. Not sure what happened to them!
