### ISSUE TITLE
Layered Sprite Dislpays

### ISSUE THREAD

**Issue by Kolterdyx** [StevePaget/Pygame_Functions#35]
Hi, I'm using pygame_functions to create a rogue-like game, and I have tried to display some sprites over others, but using the following form doesn't work:

```
class Player(pg.sprite.Sprite):
	def __init__(self):
		self._layer = 1  # set layer 1
		self.groups = game.all_sprites  # add player to the all_sprites LayeredUpdates group
		pg.sprite.Sprite.__init__(self, self.groups)
```

I have done the same for the other sprites, but it doesn't work, it still displays some sprites of the same group over and under the player one randomly

**Comment by zerokrezan** [comment]
Try to use this command to call the init method of Sprite :“super(Player, self).__init__()“ below your first function:“def __init__(self):“


Maybe this can help you too:
„all_sprites = pygame.sprite.Group()
player = Player()
all_sprites.add(player)“



Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Kolterdyx <notifications@github.com>
Gesendet: Saturday, April 4, 2020 11:15:33 PM
An: StevePaget/Pygame_Functions <Pygame_Functions@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [StevePaget/Pygame_Functions] Layered Sprite Dislpays (#35)


Hi, I'm using pygame_functions to create a rogue-like game, and I have tried to display some sprites over others, but using the following form doesn't work:

class Player(pg.sprite.Sprite):
        def __init__(self):
                self._layer = 1  # set layer 1
                self.groups = game.all_sprites  # add player to the all_sprites LayeredUpdates group
                pg.sprite.Sprite.__init__(self, self.groups)


I have done the same for the other sprites, but it doesn't work, it still displays some sprites of the same group over and under the player one randomly

**Comment by StevePaget** [comment]
Closing this as it doesn't seem to be an issue with pygame_functions
