### ISSUE TITLE
show TextBox not working, not able to use pygame_functions

### ISSUE THREAD

**Issue by BhavikMangla** [StevePaget/Pygame_Functions#36]
Traceback (most recent call last):
  File "C:/Users/Bhavik Mangla/Desktop/PycharmProjects/speedtest/main.py", line 24, in <module>
    showTextBox(wordBox)
  File "C:\Users\Bhavik Mangla\Desktop\PycharmProjects\pygame_functions.py", line 663, in showTextBox
    updateDisplay()
  File "C:\Users\Bhavik Mangla\Desktop\PycharmProjects\pygame_functions.py", line 674, in updateDisplay
    spriteRects = spriteGroup.draw(screen)
  File "C:\Users\Bhavik Mangla\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pygame\sprite.py", line 569, in draw
    surface_blit = surface.blit
AttributeError: 'str' object has no attribute 'blit'

**Comment by BhavikMangla** [comment]
Can you please identify the error in this and correct it:-
I think the error is here...
def updateDisplay():
    global background
    spriteRects = spriteGroup.draw(screen)
    textboxRects = textboxGroup.draw(screen)
    pygame.display.update()
    keys = pygame.key.get_pressed()
    if (keys[pygame.K_ESCAPE]):
        pygame.quit()
        sys.exit()
    spriteGroup.clear(screen, background.surface)
    textboxGroup.clear(screen, background.surface)

**Comment by BhavikMangla** [comment]
Can you please identify the error in this and correct it:-  
I think the error is here...

 def draw(self, surface):
       spritedict = self.spritedict
       surface_blit = surface.blit
       dirty = self.lostsprites
       self.lostsprites = []
       dirty_append = dirty.append
       for s in self.sprites():
           r = spritedict[s]
           newrect = surface_blit(s.image, s.rect)
           if r:
               if newrect.colliderect(r):
                   dirty_append(newrect.union(r))
               else:
                   dirty_append(newrect)
                   dirty_append(r)
           else:
               dirty_append(newrect)
           spritedict[s] = newrect
       return dirty

**Comment by StevePaget** [comment]
The error is probably in your program rather than pygame. Could you post
your code here and I'll have a look.

**Comment by BhavikMangla** [comment]
import pygame
from pygame import mixer
from pygame_functions import *
import random

# Initialize the pygame
pygame.init()

#Create the screen
screen = pygame.display.set_mode((1284,588))

#Title and Icon
pygame.display.set_caption("Typing Speed Test")
icon = pygame.image.load('icon.png')
pygame.display.set_icon(icon)

#Restart Icon
restart = pygame.image.load('restart.png')
x=850
y=520

#TextInput
wordBox = makeTextBox(10,80,300,0,"Enter text here",0,24)
showTextBox(wordBox)
entry = textBoxInput(wordBox)

#Background Image
Background = pygame.image.load('Background2.png')

#Backgroung Sound
mixer.music.load('Background.wav')
mixer.music.play(-1)

#Display Restart icon
def restart1():
    screen.blit(restart,(x,y))

#Display Paragraph
def showpara():
    sentence1= "Coronaviruses are a family of viruses that range from the common cold to "
    sentence2= "MERS coronavirus, which is Middle East Respiratory Syndrome coronavirus "
    sentence3= "and SARs, Severe acute respiratory syndrome coronavirus. "
    font = pygame.font.Font('freesansbold.ttf', 25)
    sentence1 = font.render(sentence1, True, (0, 255, 255))
    sentence2 = font.render(sentence2, True, (0, 255, 255))
    sentence3 = font.render(sentence3, True, (0, 255, 255))
    screen.blit(sentence1, [300, 200])
    screen.blit(sentence2, [300, 230])
    screen.blit(sentence3, [300, 260])








#Game Loop
running = True
while running:
    # Background colour(RGB)
    screen.fill((0, 0, 0))

    # Display Background Image
    screen.blit(Background, (0, 0))

    #Display Para
    showpara()

    # ARROW FUNCTIONALITY
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False



    restart1()
    pygame.display.update()

**Comment by BhavikMangla** [comment]
import pygame
from pygame import mixer
from pygame_functions import *
import random

# Initialize the pygame
pygame.init()

#Create the screen
screen = pygame.display.set_mode((1284,588))

#Title and Icon
pygame.display.set_caption("Typing Speed Test")
icon = pygame.image.load('icon.png')
pygame.display.set_icon(icon)

#Restart Icon
restart = pygame.image.load('restart.png')
x=850
y=520

#TextInput
wordBox = makeTextBox(10,80,300,0,"Enter text here",0,24)
showTextBox(wordBox)
entry = textBoxInput(wordBox)

#Background Image
Background = pygame.image.load('Background2.png')

#Backgroung Sound
mixer.music.load('Background.wav')
mixer.music.play(-1)

#Display Restart icon
def restart1():
    screen.blit(restart,(x,y))

#Display Paragraph
def showpara():
    sentence1= "Coronaviruses are a family of viruses that range from the common cold to "
    sentence2= "MERS coronavirus, which is Middle East Respiratory Syndrome coronavirus "
    sentence3= "and SARs, Severe acute respiratory syndrome coronavirus. "
    font = pygame.font.Font('freesansbold.ttf', 25)
    sentence1 = font.render(sentence1, True, (0, 255, 255))
    sentence2 = font.render(sentence2, True, (0, 255, 255))
    sentence3 = font.render(sentence3, True, (0, 255, 255))
    screen.blit(sentence1, [300, 200])
    screen.blit(sentence2, [300, 230])
    screen.blit(sentence3, [300, 260])








#Game Loop
running = True
while running:
    # Background colour(RGB)
    screen.fill((0, 0, 0))

    # Display Background Image
    screen.blit(Background, (0, 0))

    #Display Para
    showpara()

    # ARROW FUNCTIONALITY
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False



    restart1()
    pygame.display.update()

**Comment by StevePaget** [comment]
The error is because you are not using pygame_functions to create your
screen. If you look at the demos, you'll see that none of them include a
setmode command. That's because pygame creates the screen for you, and then
makeTextbox works with this screen.

Have a look at the Wiki to see how to get started using the library.
