### ISSUE TITLE
Spritesheet animation not working, please help!

### ISSUE THREAD

**Issue by BaconxD** [StevePaget/Pygame_Functions#43]
from pygame_functions import *

def main():

    # setup window
    screenSize(1024, 768)
    setBackgroundColour('dark blue')

    # load player sprite
    x = 500
    y = 500
    jonas = makeSprite('guyspritesheet32.gif', 48)
    showSprite(jonas)
    moveSprite(jonas, x, y, True)

    nextFrame = clock()
    frame = 0

    # main loop
    while True:
        
        # player movement
        if clock() > nextFrame:
            frame = (frame+1) % 6
            nextFrame += 80

        if keyPressed('s'):
            changeSpriteImage(jonas, 0 * 6 + frame)
        elif keyPressed('s') and keyPressed('a'):
            changeSpriteImage(jonas, 1 * 6 + frame)
        elif keyPressed('a'):
            changeSpriteImage(jonas, 2 * 6 + frame)
        elif keyPressed('a') and keyPressed('w'):
            changeSpriteImage(jonas, 3 * 6 + frame)
        elif keyPressed('w'):
            changeSpriteImage(jonas, 4 * 6 + frame)
        elif keyPressed('w') and keyPressed('d'):
            changeSpriteImage(jonas, 5 * 6 + frame)
        elif keyPressed('d'):
            changeSpriteImage(jonas, 6 * 6 + frame)
        elif keyPressed('d') and keyPressed('s'):
            changeSpriteImage(jonas, 7 * 6 + frame)
        else:
            changeSpriteImage(jonas, 0)

        tick(60)
        endWait()

if __name__ == '__main__':
    main()

**Comment by StevePaget** [comment]
The problem might that you have endWait() within your main loop, so it's pausing as soon as the loop runs once.

Try deleting endWait() altogether. You can still quit by pressing Esc.

**Comment by BaconxD** [comment]
oh, i thought you needed the endWait() in the main loop to close the game... But I deleted it and still doesnt work.
maybe this gives you an insight, but when I take out the frames parameter in "makeSprite('guyspritesheet32.gif', 48)" the first frame actually appears, but with the 48 in there nothing appears.

**Comment by StevePaget** [comment]
I don't have a copy off the gif you're using, but if I replace it with the links.gif from the demo file this works fine (so long as you remove endWait)
I'd have to say it might be an issue with the spritesheet, but I can't suggest what it would be.

There is a logical problem with your code though:

`if keyPressed('s'):
            changeSpriteImage(jonas, 0 * 6 + frame)
        elif keyPressed('s') and keyPressed('a'):
            changeSpriteImage(jonas, 1 * 6 + frame)
       etc`

If "s" is pressed, it's going to execute the first line. It's never going to check to see if "a" is pressed because elif stops as soon as it finds a matching condition. Likewise with the other AND conditions. They're never going to be checked.

**Comment by BaconxD** [comment]
Thank you for pointing that problem!!
And about the gif problem, when I put the pygame_functions file in my pycharm project, it points me that the file is not using the math library, despite importing it. Do you think that maybe there was a problem when getting the functions file?

**Comment by CoolCat467** [comment]
But the pygame_functions library only imports pygame, os, and sys. Nowhere does it import the math module.
