### ISSUE TITLE
Error with setBackgroundImage(img), (Scrolling Background)

### ISSUE THREAD

**Issue by LeenaProxima** [StevePaget/Pygame_Functions#55]
I do not know whether this is because I am on a Chromebook or not, but every time I try to run this program, I keep getting this error:
![Screenshot 2022-04-22 8 09 24 AM](https://user-images.githubusercontent.com/95589079/164711623-7104a4ce-f9f5-40ff-ad24-25fbddb1d3a0.png)

Any ideas on how to fix it?

**Comment by StevePaget** [comment]
I can't think of anything obvious. Perhaps you could post a larger code segment?

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by LeenaProxima** [comment]
Nevermind. The issue is fixed!

**Comment by rhit-loperjc** [comment]
I have the same issue. How did you fix it?

**Comment by frankbatty** [comment]
Wow this is a while ago. I have redone the game with Unity and I am now
considering Godot. On hold for other stuff. I'll take a look. Can't promise
I will remember, or when I'll come back. But I will try.

**Comment by rhit-loperjc** [comment]
Thanks, I appreciate your effort. It seems that my pygame_functions document is missing a lot of references for some reason and I cannot figure out why

**Comment by StevePaget** [comment]
It has been a while since I used this feature. If you haven't worked it out by tomorrow I'll take a look. What are you trying to do? Is your background one image or a list of tiles?

**Comment by StevePaget** [comment]
Without any more information it's not really possible to diagnose the problem, but as a guess I would say that you have named something else "background", which is messing with pygame_functions internal code. Maybe check that.
