### ISSUE TITLE
Window Title and Image

### ISSUE THREAD

**Issue by Python-Manic-123000** [StevePaget/Pygame_Functions#6]
Could you please make it so pygame_functions allows you to change the Title (Caption) and Image (Icon) of the window.

**Comment by StevePaget** [comment]
Yes, that should be possible. Leave it with me.

**Comment by Python-Manic-123000** [comment]
Thanks

**Comment by StevePaget** [comment]
This should now be possible with setIcon and setWindowTitle.

https://github.com/StevePaget/Pygame_Functions/wiki/setIcon
https://github.com/StevePaget/Pygame_Functions/wiki/setWindowTitle
