### ISSUE TITLE
Creating AI

### ISSUE THREAD

**Issue by Kykory** [StevePaget/Pygame_Functions#7]
Hi, i am trying to create an AI that is using the textbox. She's just returning number
i am using those instructions:

event=[ ]
u=[u'0',u'1',u'2',u'3',u'4',u'5',u'6',u'7',u'8',u'9']
for i in range(10):
  event+=[pygame.event.Event(pygame.KEYDOWN,key=pygame.K_i, mod=0 , unicode=u[i])

def ask_auto(question,reponse):
  liste_reponse=list(reponse)
  taille=len(liste_reponse)
  for i in range(taille):
    wordBox = pg.makeTextBox(300, 10, 300, 0, question, 15, 20)
    pg.showTextBox(wordBox)
    entry = pg.textBoxInput(wordBox)
    evenement=event[int(liste_reponse[i])]
    pygame.event.post(evenement)
  evenement=pygame.event.Event(pygame.KEYDOWN,key=pygame.K_RETURN, mod=0 , unicode=u'')
  pygame.event.post(evenement)
  wordBox = pg.makeTextBox(300, 10, 300, 0, "", 15, 20)
  pg.showTextBox(wordBox)

but it's not working...
Do you have an idea of what went wrong? i think it's about my pygame.event.Event() and the way you are saving the keyboard entry but i don't know what to change...

(i am french so reponse = answer and evenement = event in French)
(and sorry for my bad english)

**Comment by Kykory** [comment]
I don't know what happen but it is now working ^^'

**Comment by StevePaget** [comment]
Oh, cool. I was going to look at this today!

**Comment by Kykory** [comment]
Thanks!
i share my code of the fonction here if you want to understand what i did:

events=[]
for i in range(10):
event+=[pygame.event.Event(pygame.KEYDOWN,key=pygame.K_i, mod=0 , unicode=u''.format(i))]

def ask_auto(question,reponse): #la même mais avec l'ia
     liste_reponse=list(reponse)
     taille=len(liste_reponse)
     for i in range(taille):
           wordBox = pg.makeTextBox(300, 10, 600, 0, question, 15, 20)
           pg.showTextBox(wordBox)
           evenement=event[int(liste_reponse[i])]
           pygame.event.post(evenement)
     evenement=pygame.event.Event(pygame.KEYDOWN,key=pygame.K_RETURN, mod=0)
     pygame.event.post(evenement)
     pygame.time.delay(1000)
     entry = pg.textBoxInput(wordBox)
     #print(entry)
     wordBox = pg.makeTextBox(300, 10, 600, 0, "", 15, 20)  
     pg.showTextBox(wordBox)
