### ISSUE TITLE
pygame.transform.flip()

### ISSUE THREAD

**Issue by Galtrox** [StevePaget/Pygame_Functions#9]
I was gonna do a pull request but it seems that you disabled it.  

This would implement the flip function 
`def transformFlip(sprite, horizontal=True, vertical=False):
 sprite.image = pygame.transform.flip(sprite.image, horizontal, vertical)
 updateDisplay()`

There is only one problem is that when fliped it wants to change back to the non fliped image like so
`        if keyPressed("a"):
            transformFlip(Sprite, True, False)`
![w9zsh](https://user-images.githubusercontent.com/16389426/38990365-e53a7bba-43d1-11e8-84c6-2a8dbb844f54.gif)

**Comment by StevePaget** [comment]
I wasn't aware that pull requests were off. That's weird. Thanks for the
suggestion. I'll take a look.

**Comment by Galtrox** [comment]
Perfect! thank you
